{% set name = "mesaLib" %}
{% set version = "18.1.4" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.gz
  sha256: 8acd42e4ac4d1e96ed22344073b3d4fef03d10f225f4eaf3f88c001dfc10e2db

build:
  skip: True  # [win]
  number: 0
  track_features:
      - mesalib

requirements:
  build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - pkgconfig
  host:
      - python 2.*
      - mako
      - pthread-stubs
      - llvmdev
      - expat

test:
  commands:
      - test -f $PREFIX/lib/libOSMesa32${SHLIB_EXT}  # [unix]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - doutriaux1
      - dnadeau4
      - sankhesh
      - danlipsa
