travis:
  secure:
    BINSTAR_TOKEN: gdZnmPFeQhUlD8PSft7O1tmx+7B3QRcCD7zbC9int3/D38wpd0XBIMxkLgdQnjOBgIq2DPCXcQzRp2Yb2JtL9Ep8/f5lRdgLxSORm4VhqwgRg16eLWXhzeo/0XtdF/UOR3X8LsBifn+hXrQ1hlnVZl1l024fGpZvmR2x9xLJygeGN12ww9d+P6FgXt/4Evnk9O+eu1mlxbPmaEjDCxp+2cg1HXP+ymuRz2Q3RSrLR7B9Pkwd6uG37MgMs9cy9fleZuCGTWIK8JlghxkUmi3/fOSZEMgmBWS+y3tKWiV6Uc5Zd4lQNeEKBpOakmVmzYt5yPIjdVY4ratV4PDVdzJFxhHbwI9FoG7RX/J4W+Z2qaSpSWhTtPHmQVNqjYSRf0QiEQRTFwZBpsznqlKm5UHewdh8GktoQuwMvL3ySWoMUQ6GPCeE0rNDSDY+BwTLkjVecHQ0lR/jMbdN00sgPyCpRxioBAweIH5Ki4sIlthQ1WzbyBeGrdsxpuShXICynz3MYxkC7I6JAivL9A6a4ywOlc7Yk4BzI4JoCxfV00DJQ6p+rYRv1aMxo+PpHr9ZO4VkQJiTzA1NV1v2amIbKAUN7gjOqhz4YRtpXM2PDIOhZkSPIi3+WeLTqJ+TZB3WO7woS7XY9Ou6oJlhGND/mUr5Rxu797gLbxrpxEidQSkg5dI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
